/**************************************************************
* 1. Jira Ticket(s) that relates to this class
*    
*
* 2. Description - Custom exception class 
*
*
*
* 3. Objects referenced
*    -ECOM_Application_logs__c
*
* 4. Callouts to additional Components (including their methods) or None:
*    - None
*    
*
* 5. Dependant Class(es):
*    - ECOM_LoginController
*
* 6. Test Class Name: 
*
* 7. Is @Invocable: No
*
* 8. Author Name(s):
*    - Vasudev 2024.04.29
* 	 -

*************************************************************/
public class ECOM_SystemException extends Exception {

    
}